# Generated by Django 6.0.7 on 2026-07-25 03:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Annee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valeur', models.IntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Concours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Epreuve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255)),
                ('sujet_pdf_url', models.URLField()),
                ('corrige_pdf_url', models.URLField()),
                ('corrige_video_hls_id', models.CharField(max_length=255)),
                ('annee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='epreuves', to='catalog.annee')),
                ('concours', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='epreuves', to='catalog.concours')),
            ],
            options={
                'unique_together': {('concours', 'annee', 'titre')},
            },
        ),
    ]
