# Generated by Django 6.0.7 on 2026-07-25 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('STUDENT', 'Étudiant'), ('ADMIN', 'Administrateur')], default='STUDENT', max_length=20),
        ),
    ]
